#spring:
#  datasource:  
#    url=jdbc:mysql://remotemysql.com/KADnfGw78t?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username=KADnfGw78t
#    password=tzIU24jalm
#    driver-class-name=com.mysql.jdbc.Driver
#  jpa:
#    database-platform=org.hibernate.dialect.MySQL5Dialect

spring.datasources:
  driver-class-name=org.h2.Driver
  url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  username=sa
  password=sa

spring:
  jpa:
    hibernate.ddl-auto=update
    show-sql=true
  port=8082

logging:
  level.root=INFO
  level.pl.ideopolis.webScraperTGE=INFO
#  file=
#  file.max-size=
#  file.max-history=
#  path=